version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: microservice-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/php.ini
    environment:
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: microservice
      DB_USERNAME: microservice
      DB_PASSWORD: secret
      REDIS_HOST: redis
      REDIS_PASSWORD: null
      REDIS_PORT: 6379
    networks:
      - microservice-network
    depends_on:
      - mysql
      - redis

  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    container_name: microservice-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: microservice
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_PASSWORD: secret
      MYSQL_USER: microservice
    volumes:
      - ./docker/mysql:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - microservice-network

  redis:
    image: redis:alpine
    container_name: microservice-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - ./docker/redis:/data
    networks:
      - microservice-network

  nginx:
    image: nginx:alpine
    container_name: microservice-nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - .:/var/www
      - ./docker/nginx:/etc/nginx/conf.d
    networks:
      - microservice-network
    depends_on:
      - app

  node:
    image: node:20
    ports:
      - "5173:5173" # Должен быть проброс
    container_name: microservice-node
    working_dir: /var/www
    volumes:
      - .:/var/www
      - /var/www/node_modules
    networks:
      - microservice-network
    command: sh -c "npm install && npm run dev"
    environment:
      - VITE_APP_URL=http://localhost:8080
      - VITE_DEV_SERVER_HOST=0.0.0.0

networks:
  microservice-network:
    driver: bridge